import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";

import Script from "next/script";

import { Navbar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Script src="darkmode.js" />
            <Script src="sectionManager.js" />
            <Script src="https://kit.fontawesome.com/f86b390e31.js" crossOrigin="anonymous" />

            <html lang="en">
                <body className={inter.className + " dark"}>
                    <Navbar />
                    {children}
                </body>
            </html>
        </>
    );
}
